id: node.link.default
uuid: 5eb6539f-507a-4cbe-a132-505eb56d52e2
targetEntityType: node
bundle: link
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: '0'
    settings:
      rows: '9'
      summary_rows: '3'
      placeholder: ''
