id: node.article.default
uuid: e39b2ab2-0df4-4646-8a23-35c37a4633ef
targetEntityType: node
bundle: article
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: '0'
    settings:
      rows: '9'
      summary_rows: '3'
      placeholder: ''
