id: node.location.default
uuid: c51ef4b8-95b2-4f1c-9207-7c6c1cf7690a
targetEntityType: node
bundle: location
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: '0'
    settings:
      rows: '9'
      summary_rows: '3'
      placeholder: ''
