id: node.group.default
uuid: 0a09a0f1-bfe8-4b84-ae00-dde2cbdfa363
targetEntityType: node
bundle: group
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: '0'
    settings:
      rows: '9'
      summary_rows: '3'
      placeholder: ''
