id: node.individual.body
uuid: 1fb641d6-a30c-46c5-b000-b4c1b7f04fb5
status: '1'
langcode: en
field_uuid: 5d0a5620-619a-4840-8f01-1fa7d7bf36f2
entity_type: node
bundle: individual
label: Body
description: ''
required: '0'
default_value: {  }
default_value_function: ''
settings:
  display_summary: '1'
  text_processing: '1'
  user_register_form: '0'
field_type: text_with_summary
