id: node.group.body
uuid: 9ddf69d6-34eb-4461-9900-c263a2f0dc1d
status: '1'
langcode: en
field_uuid: 5d0a5620-619a-4840-8f01-1fa7d7bf36f2
entity_type: node
bundle: group
label: Body
description: ''
required: '0'
default_value: {  }
default_value_function: ''
settings:
  display_summary: '1'
  text_processing: '1'
  user_register_form: '0'
field_type: text_with_summary
